AllCops:
  Exclude:
    - Gemfile

require:
  - rubocop-rspec
  - rubocop
  - rubocop-performance

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/InstanceVariable:
 Enabled: false

Metrics/LineLength:
  Max: 200