AllCops:
  Exclude:
    - Gemfile

require:
  - rubocop-rspec
  - rubocop
  - rubocop-performance

RSpec/HookArgument:
  EnforcedStyle: context

RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false  

RSpec/DescribeClass:
  Enabled: false

RSpec/InstanceVariable:
 Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 220
